# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: node:6.9.4
image: devfubar/docker-aws-api

pipelines:
  branches:
    master:            
      - step:
          name: Deploy to Prod
          deployment: staging
          # trigger: manual
          caches:
            - node
          script:
            # --- # build # --- #
            - npm install
            - npm run build
            # --- # set develop variables # --- #
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_MLIBRE
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_MLIBRE
            # --- # deploy # --- #
            - aws s3 cp build/ s3://weather.jesusalpino.com --recursive
            - aws cloudfront create-invalidation --distribution-id E3HNR6GY6Y2C7D --paths /index.html /manifest.json /static/*